# Generated by Django 5.1.6 on 2025-03-18 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCategoryVO",
            fields=[
                ("subcategory_id", models.AutoField(primary_key=True, serialize=False)),
                ("subcategory_name", models.CharField(max_length=100)),
                (
                    "subcategory_description",
                    models.TextField(blank=True, default="No description provided"),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("modify_at", models.DateTimeField(auto_now=True)),
                (
                    "subcategory_category_vo",
                    models.ForeignKey(
                        db_column="subcategory_category_vo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.categoryvo",
                    ),
                ),
            ],
            options={
                "db_table": "sub_category_table",
            },
        ),
    ]
