# Generated by Django 5.1.6 on 2025-03-10 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_rename_created_on_categoryvo_create_at_and_more'),
        ('subcategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVO',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_quantity', models.IntegerField()),
                ('product_image_name', models.ImageField(upload_to='')),
                ('product_image_path', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.categoryvo')),
                ('product_subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subcategory.subcategoryvo')),
            ],
            options={
                'db_table': 'product_table',
            },
        ),
    ]
