# Generated by Django 5.1.6 on 2025-03-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginVO',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_username', models.CharField(max_length=120, unique=True)),
                ('login_password', models.CharField(max_length=120)),
                ('login_role', models.CharField(max_length=120)),
                ('login_status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Login',
                'verbose_name_plural': 'Logins',
                'db_table': 'login&register',
            },
        ),
    ]
