# Generated by Django 5.1.6 on 2025-03-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginvo',
            table='login_table',
        ),
    ]
