# Generated by Django 5.1.6 on 2025-03-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryVO",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=255, unique=True)),
                ("category_description", models.TextField(max_length=255)),
                ("is_deleted", models.BooleanField(default=False)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("modify_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "category_table",
            },
        ),
    ]
