# Generated by Django 5.1.6 on 2025-03-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryvo',
            old_name='created_on',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='categoryvo',
            old_name='modified_on',
            new_name='modify_at',
        ),
    ]
