# Generated by Django 5.1.6 on 2025-03-18 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterVO",
            fields=[
                ("register_id", models.AutoField(primary_key=True, serialize=False)),
                ("register_firstname", models.CharField(max_length=120)),
                ("register_lastname", models.CharField(max_length=120)),
                ("register_gender", models.CharField(max_length=120)),
                ("register_email", models.EmailField(max_length=254, unique=True)),
                ("register_phone", models.CharField(max_length=11)),
                ("id_delete", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "register_login_vo",
                    models.ForeignKey(
                        db_column="register_login_vo",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="login.loginvo",
                    ),
                ),
            ],
            options={
                "db_table": "register_table",
                "indexes": [
                    models.Index(
                        fields=["register_email"], name="register_ta_registe_6182eb_idx"
                    ),
                    models.Index(
                        fields=["register_login_vo"],
                        name="register_ta_registe_2863ab_idx",
                    ),
                ],
            },
        ),
    ]
