# Generated by Django 5.1.6 on 2025-03-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registervo',
            new_name='register_ta_registe_6182eb_idx',
            old_name='register_registe_0a7dd5_idx',
        ),
        migrations.RenameIndex(
            model_name='registervo',
            new_name='register_ta_registe_2863ab_idx',
            old_name='register_registe_f1ee05_idx',
        ),
        migrations.AlterModelTable(
            name='registervo',
            table='register_table',
        ),
    ]
